

trigger:
- master

pool:
  name: MOSHE

steps:
- script: git clone --branch master https://github.com/moshe322/webservice-test.git
  displayName: ls -la

- task: Maven@4
  inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Path'
      mavenSetM2Home: true
      mavenAuthenticateFeed: true
      effectivePomSkip: true
      sonarQubeRunAnalysis: false
 